// src/lib/db/types.generated.ts
//
// GENERATED FILE — do not hand-edit (BP-002 `## Public interface`:
// "Generated from the applied schema by `supabase gen types typescript`.
// Checked in, never hand-edited").
//
// **Fact, not a claim (rule 1.2):** the Supabase CLI and Docker are both
// unavailable on this build host (owner ruling, 2026-09-03), so
// `supabase gen types typescript --local` did not run here. This file was
// generated by postgres-meta 0.99 (the same generator the CLI calls) at
// `http://127.0.0.1:8090/generators/typescript`, run over the schema
// applied by `00000000000001_baseline.sql` and `00000000000002_rls.sql` on
// 2026-09-03, via `substrate/pgmeta/gen-types.sh` — emitting the identical
// `Database` type `supabase gen types typescript --local` would for the
// same applied schema. Regenerate with `npm run db:types` once the CLI is
// available; until then, `substrate/pgmeta/gen-types.sh` is the equivalent
// this repository's own tests hold it to (`tests/db/clients.test.ts`'s
// staleness check).

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      destinations: {
        Row: {
          config: Json | null
          created_at: string
          health: string
          id: string
          kind: string
          site_id: string
        }
        Insert: {
          config?: Json | null
          created_at?: string
          health?: string
          id?: string
          kind: string
          site_id: string
        }
        Update: {
          config?: Json | null
          created_at?: string
          health?: string
          id?: string
          kind?: string
          site_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "destinations_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      drafts: {
        Row: {
          body_md: string | null
          cost_cents: number
          created_at: string
          grounded_fact: Json | null
          id: string
          meta: Json | null
          opportunity_id: string
          scheduled_for: string | null
          site_id: string
          state: string
          title: string
          veto_deadline: string | null
        }
        Insert: {
          body_md?: string | null
          cost_cents?: number
          created_at?: string
          grounded_fact?: Json | null
          id?: string
          meta?: Json | null
          opportunity_id: string
          scheduled_for?: string | null
          site_id: string
          state: string
          title: string
          veto_deadline?: string | null
        }
        Update: {
          body_md?: string | null
          cost_cents?: number
          created_at?: string
          grounded_fact?: Json | null
          id?: string
          meta?: Json | null
          opportunity_id?: string
          scheduled_for?: string | null
          site_id?: string
          state?: string
          title?: string
          veto_deadline?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "drafts_opportunity_id_fkey"
            columns: ["opportunity_id"]
            isOneToOne: false
            referencedRelation: "opportunities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "drafts_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          consented_at: string | null
          converted_at: string | null
          draft_sent_at: string | null
          email: string
          id: string
          scan_id: string
        }
        Insert: {
          consented_at?: string | null
          converted_at?: string | null
          draft_sent_at?: string | null
          email: string
          id?: string
          scan_id: string
        }
        Update: {
          consented_at?: string | null
          converted_at?: string | null
          draft_sent_at?: string | null
          email?: string
          id?: string
          scan_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "leads_scan_id_fkey"
            columns: ["scan_id"]
            isOneToOne: false
            referencedRelation: "scans"
            referencedColumns: ["id"]
          },
        ]
      }
      opportunities: {
        Row: {
          acceptance: Json | null
          created_at: string
          effort: string | null
          evidence: Json | null
          family: string
          fit_band: string | null
          id: string
          proposed_slug: string
          scan_id: string
          site_id: string
          status: string
          target_query: string
          title: string
          type: string
          volume: number | null
        }
        Insert: {
          acceptance?: Json | null
          created_at?: string
          effort?: string | null
          evidence?: Json | null
          family: string
          fit_band?: string | null
          id?: string
          proposed_slug: string
          scan_id: string
          site_id: string
          status?: string
          target_query: string
          title: string
          type: string
          volume?: number | null
        }
        Update: {
          acceptance?: Json | null
          created_at?: string
          effort?: string | null
          evidence?: Json | null
          family?: string
          fit_band?: string | null
          id?: string
          proposed_slug?: string
          scan_id?: string
          site_id?: string
          status?: string
          target_query?: string
          title?: string
          type?: string
          volume?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "opportunities_scan_id_fkey"
            columns: ["scan_id"]
            isOneToOne: false
            referencedRelation: "scans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opportunities_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      publications: {
        Row: {
          destination: string
          draft_id: string
          id: string
          live_url: string | null
          mode: string
          published_at: string | null
          site_id: string
          unpublished_at: string | null
          verify: Json | null
        }
        Insert: {
          destination: string
          draft_id: string
          id?: string
          live_url?: string | null
          mode: string
          published_at?: string | null
          site_id: string
          unpublished_at?: string | null
          verify?: Json | null
        }
        Update: {
          destination?: string
          draft_id?: string
          id?: string
          live_url?: string | null
          mode?: string
          published_at?: string | null
          site_id?: string
          unpublished_at?: string | null
          verify?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "publications_draft_id_fkey"
            columns: ["draft_id"]
            isOneToOne: false
            referencedRelation: "drafts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "publications_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      scans: {
        Row: {
          cost_cents: number
          created_at: string
          domain: string
          drivers: Json | null
          id: string
          report: Json | null
          score: number | null
          site_id: string | null
          status: string
          tier: string
        }
        Insert: {
          cost_cents?: number
          created_at?: string
          domain: string
          drivers?: Json | null
          id?: string
          report?: Json | null
          score?: number | null
          site_id?: string | null
          status: string
          tier: string
        }
        Update: {
          cost_cents?: number
          created_at?: string
          domain?: string
          drivers?: Json | null
          id?: string
          report?: Json | null
          score?: number | null
          site_id?: string | null
          status?: string
          tier?: string
        }
        Relationships: [
          {
            foreignKeyName: "scans_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      sites: {
        Row: {
          category: string | null
          competitors: NonNullable<Json>
          created_at: string
          do_not_claim: NonNullable<Json>
          domain: string
          id: string
          mode: string
          publish_time: string
          user_id: string
          veto_hours: number
          voice_text: string | null
        }
        Insert: {
          category?: string | null
          competitors?: NonNullable<Json>
          created_at?: string
          do_not_claim?: NonNullable<Json>
          domain: string
          id?: string
          mode?: string
          publish_time?: string
          user_id: string
          veto_hours?: number
          voice_text?: string | null
        }
        Update: {
          category?: string | null
          competitors?: NonNullable<Json>
          created_at?: string
          do_not_claim?: NonNullable<Json>
          domain?: string
          id?: string
          mode?: string
          publish_time?: string
          user_id?: string
          veto_hours?: number
          voice_text?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          deleted_at: string | null
          email: string
          id: string
          plan_status: string
          stripe_customer_id: string | null
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          email: string
          id?: string
          plan_status: string
          stripe_customer_id?: string | null
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          email?: string
          id?: string
          plan_status?: string
          stripe_customer_id?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
